var dir_7f19fe0488f3daa36ae73de472a8d793 =
[
    [ "BNO08xReports.hpp", "_b_n_o08x_reports_8hpp.html", null ],
    [ "BNO08xRpt.hpp", "_b_n_o08x_rpt_8hpp.html", "_b_n_o08x_rpt_8hpp" ],
    [ "BNO08xRptAcceleration.hpp", "_b_n_o08x_rpt_acceleration_8hpp.html", "_b_n_o08x_rpt_acceleration_8hpp" ],
    [ "BNO08xRptActivityClassifier.hpp", "_b_n_o08x_rpt_activity_classifier_8hpp.html", "_b_n_o08x_rpt_activity_classifier_8hpp" ],
    [ "BNO08xRptARVRStabilizedGameRV.hpp", "_b_n_o08x_rpt_a_r_v_r_stabilized_game_r_v_8hpp.html", "_b_n_o08x_rpt_a_r_v_r_stabilized_game_r_v_8hpp" ],
    [ "BNO08xRptARVRStabilizedRV.hpp", "_b_n_o08x_rpt_a_r_v_r_stabilized_r_v_8hpp.html", "_b_n_o08x_rpt_a_r_v_r_stabilized_r_v_8hpp" ],
    [ "BNO08xRptCalGyro.hpp", "_b_n_o08x_rpt_cal_gyro_8hpp.html", "_b_n_o08x_rpt_cal_gyro_8hpp" ],
    [ "BNO08xRptCalMagnetometer.hpp", "_b_n_o08x_rpt_cal_magnetometer_8hpp.html", "_b_n_o08x_rpt_cal_magnetometer_8hpp" ],
    [ "BNO08xRptGameRV.hpp", "_b_n_o08x_rpt_game_r_v_8hpp.html", "_b_n_o08x_rpt_game_r_v_8hpp" ],
    [ "BNO08xRptGravity.hpp", "_b_n_o08x_rpt_gravity_8hpp.html", "_b_n_o08x_rpt_gravity_8hpp" ],
    [ "BNO08xRptIGyroRV.hpp", "_b_n_o08x_rpt_i_gyro_r_v_8hpp.html", "_b_n_o08x_rpt_i_gyro_r_v_8hpp" ],
    [ "BNO08xRptLinearAcceleration.hpp", "_b_n_o08x_rpt_linear_acceleration_8hpp.html", "_b_n_o08x_rpt_linear_acceleration_8hpp" ],
    [ "BNO08xRptRawMEMSAccelerometer.hpp", "_b_n_o08x_rpt_raw_m_e_m_s_accelerometer_8hpp.html", "_b_n_o08x_rpt_raw_m_e_m_s_accelerometer_8hpp" ],
    [ "BNO08xRptRawMEMSGyro.hpp", "_b_n_o08x_rpt_raw_m_e_m_s_gyro_8hpp.html", "_b_n_o08x_rpt_raw_m_e_m_s_gyro_8hpp" ],
    [ "BNO08xRptRawMEMSMagnetometer.hpp", "_b_n_o08x_rpt_raw_m_e_m_s_magnetometer_8hpp.html", "_b_n_o08x_rpt_raw_m_e_m_s_magnetometer_8hpp" ],
    [ "BNO08xRptRV.hpp", "_b_n_o08x_rpt_r_v_8hpp.html", "_b_n_o08x_rpt_r_v_8hpp" ],
    [ "BNO08xRptRVGeneric.hpp", "_b_n_o08x_rpt_r_v_generic_8hpp.html", "_b_n_o08x_rpt_r_v_generic_8hpp" ],
    [ "BNO08xRptRVGeomag.hpp", "_b_n_o08x_rpt_r_v_geomag_8hpp.html", "_b_n_o08x_rpt_r_v_geomag_8hpp" ],
    [ "BNO08xRptShakeDetector.hpp", "_b_n_o08x_rpt_shake_detector_8hpp.html", "_b_n_o08x_rpt_shake_detector_8hpp" ],
    [ "BNO08xRptStabilityClassifier.hpp", "_b_n_o08x_rpt_stability_classifier_8hpp.html", "_b_n_o08x_rpt_stability_classifier_8hpp" ],
    [ "BNO08xRptStepCounter.hpp", "_b_n_o08x_rpt_step_counter_8hpp.html", "_b_n_o08x_rpt_step_counter_8hpp" ],
    [ "BNO08xRptTapDetector.hpp", "_b_n_o08x_rpt_tap_detector_8hpp.html", "_b_n_o08x_rpt_tap_detector_8hpp" ],
    [ "BNO08xRptUncalGyro.hpp", "_b_n_o08x_rpt_uncal_gyro_8hpp.html", "_b_n_o08x_rpt_uncal_gyro_8hpp" ],
    [ "BNO08xRptUncalMagnetometer.hpp", "_b_n_o08x_rpt_uncal_magnetometer_8hpp.html", "_b_n_o08x_rpt_uncal_magnetometer_8hpp" ]
];