var annotated_dup =
[
    [ "BNO08xPrivateTypes", "namespace_b_n_o08x_private_types.html", [
      [ "bno08x_init_status_t", "struct_b_n_o08x_private_types_1_1bno08x__init__status__t.html", "struct_b_n_o08x_private_types_1_1bno08x__init__status__t" ],
      [ "bno08x_sync_ctx_t", "struct_b_n_o08x_private_types_1_1bno08x__sync__ctx__t.html", "struct_b_n_o08x_private_types_1_1bno08x__sync__ctx__t" ]
    ] ],
    [ "BNO08x", "class_b_n_o08x.html", "class_b_n_o08x" ],
    [ "bno08x_accel_t", "structbno08x__accel__t.html", "structbno08x__accel__t" ],
    [ "bno08x_activity_classifier_t", "structbno08x__activity__classifier__t.html", "structbno08x__activity__classifier__t" ],
    [ "bno08x_ang_vel_t", "structbno08x__ang__vel__t.html", "structbno08x__ang__vel__t" ],
    [ "bno08x_config_t", "structbno08x__config__t.html", "structbno08x__config__t" ],
    [ "bno08x_euler_angle_t", "structbno08x__euler__angle__t.html", "structbno08x__euler__angle__t" ],
    [ "bno08x_gyro_bias_t", "structbno08x__gyro__bias__t.html", "structbno08x__gyro__bias__t" ],
    [ "bno08x_gyro_t", "structbno08x__gyro__t.html", "structbno08x__gyro__t" ],
    [ "bno08x_magf_bias_t", "structbno08x__magf__bias__t.html", "structbno08x__magf__bias__t" ],
    [ "bno08x_magf_t", "structbno08x__magf__t.html", "structbno08x__magf__t" ],
    [ "bno08x_meta_data_t", "structbno08x__meta__data__t.html", "structbno08x__meta__data__t" ],
    [ "bno08x_quat_t", "structbno08x__quat__t.html", "structbno08x__quat__t" ],
    [ "bno08x_raw_accel_t", "structbno08x__raw__accel__t.html", "structbno08x__raw__accel__t" ],
    [ "bno08x_raw_gyro_t", "structbno08x__raw__gyro__t.html", "structbno08x__raw__gyro__t" ],
    [ "bno08x_raw_magf_t", "structbno08x__raw__magf__t.html", "structbno08x__raw__magf__t" ],
    [ "bno08x_sample_counts_t", "structbno08x__sample__counts__t.html", "structbno08x__sample__counts__t" ],
    [ "bno08x_shake_detector_t", "structbno08x__shake__detector__t.html", "structbno08x__shake__detector__t" ],
    [ "bno08x_stability_classifier_t", "structbno08x__stability__classifier__t.html", "structbno08x__stability__classifier__t" ],
    [ "bno08x_step_counter_t", "structbno08x__step__counter__t.html", "structbno08x__step__counter__t" ],
    [ "bno08x_tap_detector_t", "structbno08x__tap__detector__t.html", "structbno08x__tap__detector__t" ],
    [ "BNO08xCbGeneric", "class_b_n_o08x_cb_generic.html", "class_b_n_o08x_cb_generic" ],
    [ "BNO08xCbParamRptID", "class_b_n_o08x_cb_param_rpt_i_d.html", "class_b_n_o08x_cb_param_rpt_i_d" ],
    [ "BNO08xCbParamVoid", "class_b_n_o08x_cb_param_void.html", "class_b_n_o08x_cb_param_void" ],
    [ "BNO08xRpt", "class_b_n_o08x_rpt.html", "class_b_n_o08x_rpt" ],
    [ "BNO08xRptAcceleration", "class_b_n_o08x_rpt_acceleration.html", "class_b_n_o08x_rpt_acceleration" ],
    [ "BNO08xRptActivityClassifier", "class_b_n_o08x_rpt_activity_classifier.html", "class_b_n_o08x_rpt_activity_classifier" ],
    [ "BNO08xRptARVRStabilizedGameRV", "class_b_n_o08x_rpt_a_r_v_r_stabilized_game_r_v.html", "class_b_n_o08x_rpt_a_r_v_r_stabilized_game_r_v" ],
    [ "BNO08xRptARVRStabilizedRV", "class_b_n_o08x_rpt_a_r_v_r_stabilized_r_v.html", "class_b_n_o08x_rpt_a_r_v_r_stabilized_r_v" ],
    [ "BNO08xRptCalGyro", "class_b_n_o08x_rpt_cal_gyro.html", "class_b_n_o08x_rpt_cal_gyro" ],
    [ "BNO08xRptCalMagnetometer", "class_b_n_o08x_rpt_cal_magnetometer.html", "class_b_n_o08x_rpt_cal_magnetometer" ],
    [ "BNO08xRptGameRV", "class_b_n_o08x_rpt_game_r_v.html", "class_b_n_o08x_rpt_game_r_v" ],
    [ "BNO08xRptGravity", "class_b_n_o08x_rpt_gravity.html", "class_b_n_o08x_rpt_gravity" ],
    [ "BNO08xRptIGyroRV", "class_b_n_o08x_rpt_i_gyro_r_v.html", "class_b_n_o08x_rpt_i_gyro_r_v" ],
    [ "BNO08xRptLinearAcceleration", "class_b_n_o08x_rpt_linear_acceleration.html", "class_b_n_o08x_rpt_linear_acceleration" ],
    [ "BNO08xRptRawMEMSAccelerometer", "class_b_n_o08x_rpt_raw_m_e_m_s_accelerometer.html", "class_b_n_o08x_rpt_raw_m_e_m_s_accelerometer" ],
    [ "BNO08xRptRawMEMSGyro", "class_b_n_o08x_rpt_raw_m_e_m_s_gyro.html", "class_b_n_o08x_rpt_raw_m_e_m_s_gyro" ],
    [ "BNO08xRptRawMEMSMagnetometer", "class_b_n_o08x_rpt_raw_m_e_m_s_magnetometer.html", "class_b_n_o08x_rpt_raw_m_e_m_s_magnetometer" ],
    [ "BNO08xRptRV", "class_b_n_o08x_rpt_r_v.html", "class_b_n_o08x_rpt_r_v" ],
    [ "BNO08xRptRVGeneric", "class_b_n_o08x_rpt_r_v_generic.html", "class_b_n_o08x_rpt_r_v_generic" ],
    [ "BNO08xRptRVGeomag", "class_b_n_o08x_rpt_r_v_geomag.html", "class_b_n_o08x_rpt_r_v_geomag" ],
    [ "BNO08xRptShakeDetector", "class_b_n_o08x_rpt_shake_detector.html", "class_b_n_o08x_rpt_shake_detector" ],
    [ "BNO08xRptStabilityClassifier", "class_b_n_o08x_rpt_stability_classifier.html", "class_b_n_o08x_rpt_stability_classifier" ],
    [ "BNO08xRptStepCounter", "class_b_n_o08x_rpt_step_counter.html", "class_b_n_o08x_rpt_step_counter" ],
    [ "BNO08xRptTapDetector", "class_b_n_o08x_rpt_tap_detector.html", "class_b_n_o08x_rpt_tap_detector" ],
    [ "BNO08xRptUncalGyro", "class_b_n_o08x_rpt_uncal_gyro.html", "class_b_n_o08x_rpt_uncal_gyro" ],
    [ "BNO08xRptUncalMagnetometer", "class_b_n_o08x_rpt_uncal_magnetometer.html", "class_b_n_o08x_rpt_uncal_magnetometer" ],
    [ "BNO08xSH2HAL", "class_b_n_o08x_s_h2_h_a_l.html", null ],
    [ "BNO08xTestHelper", "class_b_n_o08x_test_helper.html", null ],
    [ "BNO08xTestSuite", "class_b_n_o08x_test_suite.html", null ]
];